-- Base de datos de LaLiga
USE laliga;

-- Tabla de fichajes
CREATE TABLE IF NOT EXISTS laliga.fichajes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha VARCHAR(10) NOT NULL,        
  competicion VARCHAR(20) NOT NULL,
  pais VARCHAR(50) NOT NULL,
  jugador VARCHAR(100) NOT NULL,
  destino VARCHAR(100) NOT NULL,
  procedencia VARCHAR(100) NOT NULL,
  tipo VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Datos de fichajes (TODOS los registros de js/pages/fichajes.js)
INSERT INTO laliga.fichajes (fecha, competicion, pais, jugador, destino, procedencia, tipo) VALUES
('01/09/2025','LALIGA','Morocco','AZZ-EDDINE','Girona FC','MARSEILLE','Traspaso'),
('01/09/2025','LALIGA','Morocco','A. ABQAR','Getafe CF','Deportivo Alavés','Libre'),
('01/09/2025','LALIGA','Spain','MARC BERNAL','FC Barcelona','FC BARCELONA JUVENIL','Libre'),
('01/09/2025','LALIGA','Spain','JUANMI','Getafe CF','Real Betis','Libre'),
('01/09/2025','LALIGA','Cameroon','NEYOU','Getafe CF','CD Leganés','Cesión'),
('01/09/2025','LALIGA','Spain','ALEX','Getafe CF','BURGOS CF','Libre'),
('01/09/2025','LALIGA','Spain','JAVI MUÑOZ','Getafe CF','UD LAS PALMAS','Traspaso'),
('01/09/2025','LALIGA','Spain','KIKO F.','Getafe CF','Villarreal CF','Libre'),
('01/09/2025','LALIGA','Portugal','CARDOSO','Sevilla FC','OPORTO','Traspaso'),
('01/09/2025','LALIGA','France','MENDY','Sevilla FC','TRABZONSPOR','Cesión'),
('01/09/2025','LALIGA','Spain','RAMÓN MARTÍNEZ','Sevilla FC','Sevilla Atlético','Libre'),
('01/09/2025','LALIGA','Spain','JOEL ROCA','Girona FC','GIRONA FC B','Libre'),
('01/09/2025','LALIGA','Spain','C.SOLER','Real Sociedad','PSG','Traspaso'),
('01/09/2025','LALIGA','Spain','JAN VIRGILI','RCD Mallorca','MALLORCA B','Libre'),
('01/09/2025','LALIGA','Greece','ALAN MATTURRO','Levante UD','GENOA','Cesión'),
('01/09/2025','LALIGA','Argentina','NICO GONZÁLEZ','Atlético de Madrid','JUVENTUS','Cesión'),
('01/09/2025','LALIGA','Israel','SOLOMON','Villarreal CF','SPURS','Cesión'),
('01/09/2025','LALIGA','Croatia','LIVAKOVIC','Girona FC','FENERBAHÇE','Cesión'),
('01/09/2025','LALIGA','France','MIKAUTADZE','Villarreal CF','LYON','Traspaso'),
('01/09/2025','LALIGA','United Kingdom','ABU KAMARA','Getafe CF','Hull City AFC','Cesión'),
('01/09/2025','LALIGA','Spain','VENCEDOR','Levante UD','Athletic Club','Cesión'),
('01/09/2025','LALIGA','Netherlands','S. BECKER','CA Osasuna','Real Sociedad','Traspaso'),
('01/09/2025','LALIGA','Spain','BRYAN','Girona FC','SPURS','Traspaso'),
('01/09/2025','LALIGA','Netherlands','AMRABAT','Real Betis','FENERBAHÇE','Cesión'),
('01/09/2025','LALIGA','Argentina','BELTRÁN','Valencia CF','FIORENTINA','Cesión'),
('01/09/2025','LALIGA','Brazil','ALEMÃO','Rayo Vallecano','PACHUCA','Traspaso'),
('01/09/2025','LALIGA','Cameroon','ETTA EYONG','Levante UD','VILLARREAL B','Traspaso'),
('01/09/2025','LALIGA','Brazil','ANTONY','Real Betis','MAN UTD','Traspaso'),
('01/09/2025','LALIGA','Ukraine','VANAT','Girona FC','Dinamo Kiev','Traspaso'),
('01/09/2025','LALIGA','DR Congo','DIANG','Elche CF','West Brom','Libre'),
('01/09/2025','LALIGA','Spain','ARRIAGA','Levante UD','PARTIZAN','Traspaso'),
('01/09/2025','LALIGA','Argentina','LUCAS BOYÉ','Deportivo Alavés','Granada CF','Traspaso'),
('01/09/2025','LALIGA','Spain','PEDROSA','Elche CF','Sevilla FC','Traspaso'),
('01/09/2025','LALIGA','Comoros','KOYALIPOU','Levante UD','LENS','Traspaso'),
('01/09/2025','LALIGA','Finland','BERGSTROM','RCD Mallorca','CHELSEA','Traspaso'),
('01/09/2025','LALIGA','Spain','AZPILICUETA','Sevilla Atlético','Real Sociedad','Traspaso'),
('01/09/2025','LALIGA','Spain','HERRERA','Real Sociedad','Girona FC','Traspaso'),
('01/09/2025','LALIGA','Spain','JAVI LÓPEZ','Real Oviedo','Real Sociedad','Traspaso'),
('01/09/2025','LALIGA','Portugal','CARMO','Real Oviedo','NOTTINGHAM FOREST','Traspaso'),
('01/09/2025','LALIGA','Spain','DENIS SUÁREZ','Deportivo Alavés','Villarreal CF','Traspaso'),
('01/09/2025','LALIGA','Nigeria','OLUWASEYI','Villarreal CF','Minnesota United FC','Traspaso'),
('01/09/2025','LALIGA','Switzerland','PICKLE','RCD Espanyol de Barcelona','Unione Sportiva Cremonese','Traspaso'),
('01/09/2025','LALIGA','Germany','ODISSEAS','Sevilla FC','NEWCASTLE','Traspaso'),
('01/09/2025','LALIGA','Spain','ARNAU TENAS','Villarreal CF','PSG','Libre'),
('30/08/2025','LALIGA','Spain','MARTÍN','FC Barcelona','Real Sociedad','Traspaso'),
('29/08/2025','LALIGA','Belgium','RAMAZANI','Valencia CF','LEEDS','Cesión'),
('29/08/2025','LALIGA','Spain','URKO','RCD Espanyol de Barcelona','Real Sociedad','Traspaso'),
('29/08/2025','LALIGA','Australia','RYAN','Levante UD','LENS','Libre'),
('29/08/2025','LALIGA','Spain','OLASAGASTI','Levante UD','Real Sociedad','Traspaso'),
('29/08/2025','LALIGA','Spain','IÑAKI PEÑA','Elche CF','FC Barcelona','Cesión'),
('28/08/2025','LALIGA','Spain','PACHECO','Deportivo Alavés','Real Sociedad','Cesión'),
('28/08/2025','LALIGA','Chile','SUAZO','Sevilla FC','TOULOUSE','Libre'),
('28/08/2025','LALIGA','Spain','ALFON','Sevilla FC','Celta','Libre'),
('24/08/2025','LALIGA','Spain','ALEX MORENO','Girona FC','A VILLA','Traspaso'),
('23/08/2025','LALIGA','Spain','IKER','Levante UD','Real Betis','Cesión'),
('23/08/2025','LALIGA','Netherlands','BREKALO','Real Oviedo','FIORENTINA','Libre'),
('23/08/2025','LALIGA','United States','KOLEOSHO','RCD Espanyol de Barcelona','BURNLEY','Cesión'),
('23/08/2025','LALIGA','Spain','DAWDA','Girona FC','GIRONA FC B','Libre'),
('22/08/2025','LALIGA','Portugal','RENATO VEIGA','Villarreal CF','CHELSEA','Traspaso'),
('22/08/2025','LALIGA','Ireland','E. BAILLY','Real Oviedo','Villarreal CF','Libre'),
('22/08/2025','LALIGA','Belgium','DENDONCKER','Real Oviedo','A VILLA','Libre'),
('21/08/2025','LALIGA','Italy','KUMBULLA','RCD Mallorca','ROMA','Cesión'),
('18/08/2025','LALIGA','Portugal','ANDRÉ SILVA','Elche CF','RB LEIPZIG','Traspaso'),
('18/08/2025','LALIGA','Spain','RAFA MIR','Elche CF','Sevilla FC','Cesión'),
('18/08/2025','LALIGA','Spain','REDONDO','Elche CF','INTER MIAMI CF','Traspaso'),
('16/08/2025','LALIGA','Spain','JOAN GARCIA','FC Barcelona','RCD Espanyol de Barcelona','Pago cláusula'),
('16/08/2025','LALIGA','United Kingdom','RASHFORD','FC Barcelona','MAN UTD','Cesión'),
('15/08/2025','LALIGA','Argentina','MATIAS MORENO','Levante UD','FIORENTINA','Cesión'),
('15/08/2025','LALIGA','Nigeria','EJARIA','Real Oviedo','READING F.C.','Libre'),
('15/08/2025','LALIGA','Germany','JEREMY TOLJAN','Levante UD','SASSUOLO','Libre'),
('15/08/2025','LALIGA','Romania','RADU','Celta','VENEZIA FC','Libre'),
('15/08/2025','LALIGA','Portugal','GUEDES','Real Sociedad','WOLVES','Traspaso'),
('15/08/2025','LALIGA','Spain','B. IGLESIAS','Celta','Real Betis','Traspaso'),
('15/08/2025','LALIGA','Croatia','CALETA-CAR','Real Sociedad','LYON','Cesión'),
('15/08/2025','LALIGA','Spain','JAVI RUEDA','Celta','CELTA DE VIGO B','Libre'),
('15/08/2025','LALIGA','Spain','MANU FERNÁNDEZ','Celta','CELTA DE VIGO B','Libre'),
('15/08/2025','LALIGA','Spain','VÍCTOR G.','Levante UD','CD ELDENSE','Libre'),
('15/08/2025','LALIGA','Spain','P. CAMPOS','Levante UD','ATLÉTICO LEVANTE UD','Libre'),
('15/08/2025','LALIGA','Spain','FRAN PÉREZ','Rayo Vallecano','Valencia CF','Traspaso'),
('15/08/2025','LALIGA','Spain','MATEO JOSEPH','RCD Mallorca','LEEDS','Cesión'),
('15/08/2025','LALIGA','Spain','MARIO MARTÍN','Getafe CF','REAL MADRID CASTILLA','Cesión'),
('14/08/2025','LALIGA','Spain','M. ROMÁN','Celta','CELTA DE VIGO B','Libre'),
('14/08/2025','LALIGA','Spain','LISO','Getafe CF','REAL ZARAGOZA','Cesión'),
('14/08/2025','LALIGA','France','LÉO PETRÓT','Elche CF','SAINT-ÉTIENNE','Libre'),
('14/08/2025','LALIGA','France','BRANDON','Real Oviedo','Debreceni VSC','Traspaso'),
('14/08/2025','LALIGA','Italy','RASPADORI','Atlético de Madrid','NAPOLI','Traspaso'),
('14/08/2025','LALIGA','Dominican Republic','JUNIOR','Real Betis','LEEDS','Libre'),
('14/08/2025','LALIGA','Colombia','DEOSSA','Real Betis','MONTERREY','Traspaso'),
('14/08/2025','LALIGA','Spain','MANU SÁNCHEZ','Levante UD','Celta','Cesión'),
('14/08/2025','LALIGA','Belgium','WITSEL','Girona FC','Atlético de Madrid','Libre'),
('14/08/2025','LALIGA','United Kingdom','DOLAN','RCD Espanyol de Barcelona','BLACKBURN ROVERS','Libre'),
('14/08/2025','LALIGA','Brazil','CALEBE','Deportivo Alavés','Fortaleza Esporte Clube','Cesión'),
('14/08/2025','LALIGA','Switzerland','UGRINIC','Valencia CF','YOUNG BOYS','Traspaso'),
('14/08/2025','LALIGA','Morocco','ILYAS','Real Oviedo','GIRONA FC B','Traspaso'),
('14/08/2025','LALIGA','Argentina','VALENTIN GOMEZ','Real Betis','VÉLEZ','Pago cláusula'),
('14/08/2025','LALIGA','Spain','PAU LOPEZ','Real Betis','DEPORTIVO TOLUCA F.C.','Libre'),
('14/08/2025','LALIGA','Brazil','VITOR REIS','Girona FC','MAN CITY','Cesión'),
('14/08/2025','LALIGA','Guinea','ILAIX MORIBA','Celta','RB LEIPZIG','Traspaso'),
('13/08/2025','LALIGA','Spain','BRYAN','Celta','FC BAYERN','Cesión'),
('13/08/2025','LALIGA','Spain','GORROTXA','Real Sociedad','R. SOCIEDAD B','Libre'),
('13/08/2025','LALIGA','Spain','KARRIKABURU','Real Sociedad','R. SOCIEDAD B','Libre'),
('13/08/2025','LALIGA','Spain','A. ALTI','Villarreal CF','VILLARREAL B','Libre'),
('13/08/2025','LALIGA','Spain','V. PARADA','Deportivo Alavés','DEPORTIVO ALAVÉS','Libre'),
('13/08/2025','LALIGA','Spain','CARREIRA','Celta','CELTA DE VIGO B','Libre'),
('13/08/2025','LALIGA','Spain','GOTI','Real Sociedad','R. SOCIEDAD B','Libre'),
('13/08/2025','LALIGA','Spain','FERRAN','Celta','CLUB BRUJAS','Traspaso'),
('13/08/2025','LALIGA','Portugal','MARTIM NETO','Elche CF','BENFICA','Traspaso'),
('13/08/2025','LALIGA','Spain','ÁLVARO','Elche CF','REAL MADRID CASTILLA','Traspaso'),
('13/08/2025','LALIGA','Spain','MARC VIDAL','Celta','CELTA DE VIGO B','Libre'),
('13/08/2025','LALIGA','Spain','MARIANO','Deportivo Alavés','Sevilla FC','Libre'),
('13/08/2025','LALIGA','Spain','V. CHUST','Elche CF','CÁDIZ CF','Cesión'),
('12/08/2025','LALIGA','Argentina','COLOMBATTO','Real Oviedo','CLUB LEÓN','Cesión'),
('12/08/2025','LALIGA','Venezuela','RONDON','Real Oviedo','PACHUCA','Cesión'),
('12/08/2025','LALIGA','Serbia','ILIC','Real Oviedo','ESTRELLA ROJA','Libre'),
('12/08/2025','LALIGA','Uruguay','F. VIÑAS','Real Oviedo','CLUB LEÓN','Cesión'),
('12/08/2025','LALIGA','Spain','A. FORES','Real Oviedo','VILLARREAL B','Cesión'),
('12/08/2025','LALIGA','Spain','A. REINA','Real Oviedo','CD MIRANDÉS','Libre'),
('12/08/2025','LALIGA','Uruguay','GONZALO PETIT','Real Betis','CLUB NACIONAL DE FOOTBALL DE MONTEVIDEO','Traspaso'),
('12/08/2025','LALIGA','Nigeria','DANJUMA','Valencia CF','Villarreal CF','Traspaso'),
('12/08/2025','LALIGA','France','SANTAMARIA','Valencia CF','RENNES','Traspaso'),
('12/08/2025','LALIGA','Spain','GERMAN V.','Elche CF','VALENCIA MESTALLA','Libre'),
('12/08/2025','LALIGA','Spain','COLLADO','Real Betis','Al Akhdoud Saudi Club','Libre'),
('11/08/2025','LALIGA','Romania','MOLDOVAN','Real Oviedo','Atlético de Madrid','Cesión'),
('11/08/2025','LALIGA','Ghana','THOMAS','Villarreal CF','ARSENAL','Libre'),
('09/08/2025','LALIGA','Spain','GONZALO','Real Madrid','REAL MADRID CASTILLA','Libre'),
('08/08/2025','LALIGA','Spain','A. FORTUÑO','RCD Espanyol de Barcelona','RCD ESPANYOL B','Libre'),
('07/08/2025','LALIGA','Spain','ALEÑÁ','Deportivo Alavés','Getafe CF','Traspaso'),
('07/08/2025','LALIGA','Spain','YOUSSEF','Deportivo Alavés','REAL MADRID CASTILLA','Traspaso'),
('07/08/2025','LALIGA','Spain','RAÚL FERNÁNDEZ','Deportivo Alavés','CD MIRANDÉS','Libre'),
('07/08/2025','LALIGA','Spain','IBAÑEZ','Deportivo Alavés','CA Osasuna','Libre'),
('07/08/2025','LALIGA','Spain','ARESO','Athletic Club','CA Osasuna','Traspaso'),
('07/08/2025','LALIGA','Spain','A. ROCA','RCD Espanyol de Barcelona','RCD ESPANYOL B','Libre'),
('07/08/2025','LALIGA','Uruguay','MOURIÑO','Villarreal CF','Atlético de Madrid','Traspaso'),
('06/08/2025','LALIGA','Spain','C. ROMERO','RCD Espanyol de Barcelona','Villarreal CF','Cesión'),
('05/08/2025','LALIGA','Spain','MARC PUBILL','Atlético de Madrid','UD ALMERÍA','Traspaso'),
('04/08/2025','LALIGA','Spain','RABA','Valencia CF','CD Leganés','Libre'),
('04/08/2025','LALIGA','Spain','VÍCTOR MUÑOZ','CA Osasuna','REAL MADRID CF C','Traspaso'),
('04/08/2025','LALIGA','Slovakia','DAVID HANCKO','Atlético de Madrid','FEYENOORD','Traspaso'),
('04/08/2025','LALIGA','France','V. ROSIER','CA Osasuna','CD Leganés','Libre'),
('04/08/2025','LALIGA','Spain','I. BENITO','CA Osasuna','CLUB ATLETICO OSASUNA B','Libre'),
('04/08/2025','LALIGA','Canada','BUCHANAN','Villarreal CF','INTER','Traspaso'),
('04/08/2025','LALIGA','Spain','J. OTTO','Deportivo Alavés','PAOK','Traspaso'),
('04/08/2025','LALIGA','Spain','A. MOLEIRO','Villarreal CF','UD LAS PALMAS','Traspaso'),
('04/08/2025','LALIGA','Spain','ADAMA','Athletic Club','ATHLETIC CLUB B','Libre'),
('04/08/2025','LALIGA','Uruguay','MOURIÑO','Atlético de Madrid','Deportivo Alavés','Traspaso'),
('04/08/2025','LALIGA','France','LEMAR','Girona FC','Atlético de Madrid','Cesión'),
('04/08/2025','LALIGA','Spain','H. RINCÓN','Girona FC','ATHLETIC CLUB B','Cesión'),
('04/08/2025','LALIGA','Spain','AGIRREZABALA','Valencia CF','Athletic Club','Cesión'),
('04/08/2025','LALIGA','Spain','COPETE','Valencia CF','RCD Mallorca','Traspaso'),
('01/08/2025','LALIGA','Spain','PABLO TORRE','RCD Mallorca','FC BARCELONA B','Traspaso'),
('31/07/2025','LALIGA','Spain','RAFA MARÍN','Villarreal CF','NAPOLI','Cesión'),
('31/07/2025','LALIGA','Argentina','ALMADA','Atlético de Madrid','BOTAFOGO DE FUTEBOL E REGATAS','Traspaso'),
('31/07/2025','LALIGA','Brazil','NATAN','Real Betis','NAPOLI','Traspaso'),
('31/07/2025','LALIGA','Spain','NAVARRO','Athletic Club','MALLORCA B','Libre'),
('31/07/2025','LALIGA','Brazil','LUIZ FELIPE','Rayo Vallecano','MARSEILLE','Libre'),
('31/07/2025','LALIGA','Spain','GUMBAU','Rayo Vallecano','Granada CF','Cesión'),
('31/07/2025','LALIGA','Spain','COBA','Getafe CF','GETAFE CF B','Libre'),
('30/07/2025','LALIGA','Spain','RIQUELME','Real Betis','Atlético de Madrid','Traspaso'),
('30/07/2025','LALIGA','Spain','Á.VALLES','Real Betis','UD LAS PALMAS','Libre'),
('30/07/2025','LALIGA','Spain','R. TERRATS','RCD Espanyol de Barcelona','Villarreal CF','Cesión'),
('30/07/2025','LALIGA','Spain','C. ROMERO','Villarreal CF','VILLARREAL B','Libre'),
('28/07/2025','LALIGA','Spain','ASENCIO','Real Madrid','REAL MADRID CASTILLA','Libre'),
('24/07/2025','LALIGA','Spain','C.RIVERO','Valencia CF','ALBACETE BP','Libre'),
('23/07/2025','LALIGA','Spain','ROBERTO','RCD Espanyol de Barcelona','BRAGA','Traspaso'),
('23/07/2025','LALIGA','Argentina','A. BATALLA','Rayo Vallecano','RIVER PLATE','Traspaso'),
('22/07/2025','LALIGA','Spain','A. CARRERAS','Real Madrid','Benfica','Traspaso'),
('22/07/2025','LALIGA','United States','JOHNNY','Atlético de Madrid','Real Betis','Traspaso'),
('21/07/2025','LALIGA','Spain','MIGUEL RUBIO','RCD Espanyol de Barcelona','Granada CF','Libre'),
('21/07/2025','LALIGA','Spain','SALINAS','RCD Espanyol de Barcelona','Elche CF','Libre'),
('21/07/2025','LALIGA','Italy','RUGGERI','Atlético de Madrid','Atalanta','Traspaso'),
('21/07/2025','LALIGA','Serbia','DMITROVIC','RCD Espanyol de Barcelona','CD Leganés','Libre'),
('21/07/2025','LALIGA','Spain','KIKE G.','RCD Espanyol de Barcelona','Deportivo Alavés','Libre'),
('17/07/2025','LALIGA','Spain','JUANLU','Sevilla FC','Sevilla Atlético','Libre'),
('10/07/2025','LALIGA','Spain','ALEX. B','Atlético de Madrid','Villarreal CF','Traspaso'),
('01/07/2025','LALIGA','Argentina','J. MUSSO','Atlético de Madrid','Atalanta','Traspaso'),
('01/07/2025','LALIGA','United Kingdom','ALEXANDER-ARNOLD','Real Madrid','Liverpool','Traspaso'),
('01/07/2025','LALIGA','Spain','HUIJSEN','Real Madrid','Bournemouth','Traspaso');


